services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            target: dev # dev or prod
        volumes:
            - .:/app
        ports:
            - "19100:8000"
        tty: true

    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: app
        ports:
            - "19101:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
